"""
report_generator.py — PDF report generator for machine analytics

Generates a professional PDF report from analysis results using reportlab.
Supports multiple analysis types in one report.
"""

import io
from datetime import datetime
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, KeepTogether
)


# ------------------------------------------------------------------ #
# Colour palette
# ------------------------------------------------------------------ #
C_DARK   = colors.HexColor("#1a1a2e")
C_BLUE   = colors.HexColor("#185FA5")
C_TEAL   = colors.HexColor("#0F6E56")
C_AMBER  = colors.HexColor("#BA7517")
C_RED    = colors.HexColor("#A32D2D")
C_GREEN  = colors.HexColor("#3B6D11")
C_LIGHT  = colors.HexColor("#f8f8f8")
C_BORDER = colors.HexColor("#dddddd")
C_MUTED  = colors.HexColor("#666666")


# ------------------------------------------------------------------ #
# Styles
# ------------------------------------------------------------------ #
def _styles():
    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle(
            "title", parent=base["Title"],
            fontSize=22, textColor=C_DARK, spaceAfter=4, fontName="Helvetica-Bold"
        ),
        "subtitle": ParagraphStyle(
            "subtitle", parent=base["Normal"],
            fontSize=11, textColor=C_MUTED, spaceAfter=16, fontName="Helvetica"
        ),
        "section": ParagraphStyle(
            "section", parent=base["Heading1"],
            fontSize=13, textColor=C_BLUE, spaceBefore=14, spaceAfter=6,
            fontName="Helvetica-Bold", borderPad=2
        ),
        "subsection": ParagraphStyle(
            "subsection", parent=base["Heading2"],
            fontSize=11, textColor=C_DARK, spaceBefore=8, spaceAfter=4,
            fontName="Helvetica-Bold"
        ),
        "body": ParagraphStyle(
            "body", parent=base["Normal"],
            fontSize=9, textColor=C_DARK, spaceAfter=4, leading=14,
            fontName="Helvetica"
        ),
        "caption": ParagraphStyle(
            "caption", parent=base["Normal"],
            fontSize=8, textColor=C_MUTED, spaceAfter=2, fontName="Helvetica"
        ),
        "narrative": ParagraphStyle(
            "narrative", parent=base["Normal"],
            fontSize=10, textColor=C_DARK, spaceAfter=6, leading=15,
            fontName="Helvetica", backColor=colors.HexColor("#EDF4FF"),
            borderColor=C_BLUE, borderWidth=0.5, borderPad=8, borderRadius=4
        ),
        "bullet": ParagraphStyle(
            "bullet", parent=base["Normal"],
            fontSize=9, textColor=C_DARK, spaceAfter=3, leading=13,
            fontName="Helvetica", leftIndent=12, bulletIndent=0
        ),
        "anomaly": ParagraphStyle(
            "anomaly", parent=base["Normal"],
            fontSize=9, textColor=colors.HexColor("#7B2020"), spaceAfter=3,
            leading=13, fontName="Helvetica", backColor=colors.HexColor("#FFF0F0"),
            borderColor=C_RED, borderWidth=0.5, borderPad=6
        ),
        "footer": ParagraphStyle(
            "footer", parent=base["Normal"],
            fontSize=7, textColor=C_MUTED, alignment=TA_CENTER, fontName="Helvetica"
        ),
    }
    return styles


# ------------------------------------------------------------------ #
# Header / footer callbacks
# ------------------------------------------------------------------ #
def _make_header_footer(machine_info: dict, report_date: str):
    def _on_page(canvas, doc):
        w, h = A4
        canvas.saveState()
        # Header bar
        canvas.setFillColor(C_BLUE)
        canvas.rect(0, h - 18*mm, w, 18*mm, fill=1, stroke=0)
        canvas.setFont("Helvetica-Bold", 11)
        canvas.setFillColor(colors.white)
        canvas.drawString(15*mm, h - 11*mm,
                          f"Machine Analytics Report — {machine_info.get('machine_type','')}"
                          f"  |  {machine_info.get('machine_id','')}")
        canvas.setFont("Helvetica", 8)
        canvas.drawRightString(w - 15*mm, h - 11*mm, report_date)

        # Footer
        canvas.setFillColor(C_MUTED)
        canvas.setFont("Helvetica", 7)
        canvas.drawString(15*mm, 8*mm, "Generated by Machine Analytics — Powered by Claude")
        canvas.drawRightString(w - 15*mm, 8*mm, f"Page {doc.page}")
        canvas.setStrokeColor(C_BORDER)
        canvas.setLineWidth(0.5)
        canvas.line(15*mm, 12*mm, w - 15*mm, 12*mm)
        canvas.restoreState()
    return _on_page


# ------------------------------------------------------------------ #
# KPI table
# ------------------------------------------------------------------ #
def _kpi_table(kpis: list, styles: dict) -> Optional[Table]:
    if not kpis:
        return None
    status_color = {"normal": C_GREEN, "warning": C_AMBER, "critical": C_RED}
    status_label = {"normal": "Normal", "warning": "Warning", "critical": "Critical"}

    data = [["Parameter", "Value", "Status"]]
    for kpi in kpis:
        status = kpi.get("status", "normal")
        data.append([
            Paragraph(kpi.get("label", "—"), styles["body"]),
            Paragraph(f"<b>{kpi.get('value','—')}</b>", styles["body"]),
            Paragraph(
                f'<font color="{status_color.get(status, C_MUTED).hexval()}">'
                f'<b>{status_label.get(status,"—")}</b></font>',
                styles["body"]
            ),
        ])

    col_widths = [80*mm, 55*mm, 35*mm]
    t = Table(data, colWidths=col_widths)
    t.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, 0), C_BLUE),
        ("TEXTCOLOR",    (0, 0), (-1, 0), colors.white),
        ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",     (0, 0), (-1, 0), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, C_LIGHT]),
        ("GRID",         (0, 0), (-1, -1), 0.4, C_BORDER),
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",   (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
    ]))
    return t


# ------------------------------------------------------------------ #
# Main generator
# ------------------------------------------------------------------ #
def generate_report(
    machine_info: dict,
    multi_results: dict,
    date_range: tuple,
    data_info: Optional[dict] = None,
) -> bytes:
    """
    Generate a PDF report from multi_results dict.
    Returns PDF as bytes (for st.download_button).

    Args:
        machine_info  : {"machine_id", "machine_type", "description"}
        multi_results : {analysis_type: insights_dict, ...}
        date_range    : (start_date, end_date)
        data_info     : optional {"rows": int, "columns": list}
    """
    buf = io.BytesIO()
    report_date = datetime.now().strftime("%d %b %Y  %H:%M")
    S = _styles()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        topMargin=22*mm,
        bottomMargin=18*mm,
        leftMargin=15*mm,
        rightMargin=15*mm,
        title=f"Machine Analytics Report — {machine_info.get('machine_id','')}",
        author="Machine Analytics",
    )

    on_page = _make_header_footer(machine_info, report_date)
    story   = []

    # ---- Cover block ----
    story.append(Spacer(1, 6*mm))
    story.append(Paragraph(
        f"{machine_info.get('machine_type','Machine')} — {machine_info.get('machine_id','')}",
        S["title"]
    ))
    story.append(Paragraph(
        f"Continuous Monitoring Analytics Report  |  Generated: {report_date}",
        S["subtitle"]
    ))

    # Date range & data summary
    dr_start = str(date_range[0]) if date_range else "—"
    dr_end   = str(date_range[1]) if date_range else "—"
    summary_data = [
        ["Analysis period", f"{dr_start}  to  {dr_end}"],
        ["Machine type",    machine_info.get("machine_type", "—")],
        ["Machine ID",      machine_info.get("machine_id", "—")],
    ]
    if data_info:
        summary_data.append(["Total data rows", f"{data_info.get('rows',0):,}"])
        summary_data.append(["Parameters",      str(data_info.get('columns', 0))])

    desc = machine_info.get("description", "")
    if desc:
        base_desc = desc.split("=== PARAMETER THRESHOLDS ===")[0].strip()
        if base_desc:
            summary_data.append(["Specifications", base_desc[:200]])

    t = Table(summary_data, colWidths=[50*mm, 120*mm])
    t.setStyle(TableStyle([
        ("FONTNAME",      (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",      (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 0), (-1, -1), 9),
        ("TEXTCOLOR",     (0, 0), (0, -1), C_BLUE),
        ("ROWBACKGROUNDS",(0, 0), (-1, -1), [colors.white, C_LIGHT]),
        ("GRID",          (0, 0), (-1, -1), 0.4, C_BORDER),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(t)
    story.append(HRFlowable(width="100%", thickness=1, color=C_BLUE, spaceAfter=8))

    # ---- Analysis sections ----
    for atype, insights in multi_results.items():
        if "error" in insights:
            story.append(Paragraph(atype, S["section"]))
            story.append(Paragraph(f"Analysis failed: {insights['error']}", S["body"]))
            story.append(Spacer(1, 4*mm))
            continue

        section_items = []

        # Section heading
        section_items.append(Paragraph(atype, S["section"]))
        section_items.append(HRFlowable(width="100%", thickness=0.5, color=C_BORDER))

        # Health score / compliance bar
        score = insights.get("health_score")
        if score is not None:
            label = "Schedule compliance" if "Schedule" in atype else "Health score"
            score_color = C_GREEN if score >= 80 else C_AMBER if score >= 60 else C_RED
            score_data = [[
                Paragraph(f"{label}:", S["body"]),
                Paragraph(
                    f'<font color="{score_color.hexval()}"><b>{score} / 100</b></font>',
                    S["body"]
                ),
            ]]
            score_table = Table(score_data, colWidths=[50*mm, 120*mm])
            score_table.setStyle(TableStyle([
                ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
                ("TOPPADDING", (0,0), (-1,-1), 4),
            ]))
            section_items.append(score_table)
            section_items.append(Spacer(1, 2*mm))

        # Narrative
        narrative = insights.get("narrative", "")
        if narrative:
            section_items.append(Paragraph(narrative, S["narrative"]))
            section_items.append(Spacer(1, 3*mm))

        # KPIs
        kpis = insights.get("kpis", [])
        if kpis:
            section_items.append(Paragraph("Key performance indicators", S["subsection"]))
            kpi_t = _kpi_table(kpis, S)
            if kpi_t:
                section_items.append(kpi_t)
                section_items.append(Spacer(1, 3*mm))

        # Anomalies
        anomalies = insights.get("anomalies", [])
        if anomalies:
            section_items.append(Paragraph("Anomalies detected", S["subsection"]))
            for a in anomalies:
                text = f"<b>{a.get('parameter','—')}</b> — {a.get('description','')}"
                section_items.append(Paragraph(text, S["anomaly"]))
                section_items.append(Spacer(1, 1*mm))
            section_items.append(Spacer(1, 2*mm))

        # Key insights
        key_points = insights.get("insights", [])
        if key_points:
            section_items.append(Paragraph("Key insights", S["subsection"]))
            for point in key_points:
                section_items.append(Paragraph(f"• {point}", S["bullet"]))
            section_items.append(Spacer(1, 3*mm))

        story.append(KeepTogether(section_items[:6]))
        for item in section_items[6:]:
            story.append(item)

        story.append(Spacer(1, 4*mm))

    # ---- Build ----
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    buf.seek(0)
    return buf.read()
